### ISSUE TITLE
Runtime error for montserrat-32 font file

### ISSUE THREAD

**Issue by StampyTurtle** [craftworkgames/Samples.Extended#5]
With no additional changes, this runtime error occurs upon building and debugging the solution.

```
An unhandled exception of type 'Microsoft.Xna.Framework.Content.ContentLoadException' occurred in MonoGame.Framework.dll

Additional information: Could not load montserrat-32 asset as a non-content file!
```

Doing some research it seems this error can occur if the Content.MGCB isn't set to copy to the output directory (where it isn't in the working directory of the app). This was set in the solution to never copy, but even after changing this the same compilation error occurs.

Is there anything I'm missing that would be obvious for why I'm getting this solution? Thank you.

**Comment by craftworkgames** [comment]
That's odd. I can't see any obvious reason why it doesn't work. 
- What version of MonoGame are you running? I'm using one of the recent development builds from [here](http://www.monogame.net/downloads/) but it should also work with the latest release (3.4)
- What about Visual Studio? I'm running it out of VS2015.
- The files are definitely in [source control](https://github.com/craftworkgames/Samples.Extended/tree/master/Source/Launcher/Content)

My thinking is that the Pipeline tool isn't building the XNB files for some reason. Try opening the Content.mgcb file in the Pipeline tool and building them manually to see if there's any obvious errors.

**Comment by Ryner-Lute** [comment]
I'm having the same problem as stated above. 
Running:
* MonoGame 3.4
* VS2015 Enterprise 
* Rebuilt the files on the content manager, no Error
* nuGet restored
I rebuilt the file in the content manager and it built without problems. I also tried to delete the old xnb files and re-added montserrat-32.fnt to the content manager. As expected it rebuilt a new xnb file but the error still comes up. I'll retry this on MonoDevelop and see how it does there.

**Comment by Sejsel** [comment]
I am also getting this exception.

If I add `Content.Load<Texture2D>("axe");` on the line before `_bitmapFont = Content.Load<BitmapFont>("montserrat-32");` I get the same error for that line.
```
An unhandled exception of type 'Microsoft.Xna.Framework.Content.ContentLoadException' occurred in MonoGame.Framework.dll
Additional information: Could not load axe asset as a non-content file!
```

It seems that the files are being generated in a wrong folder. I am going to look into this a bit more.

**Comment by craftworkgames** [comment]
> I am going to look into this a bit more.

That would be great. I haven't been able to reproduce it but I'd really like to get this fixed. Thanks.

**Comment by Sejsel** [comment]
Alright, I managed to find the issue.
The issue is a version mismatch between the Content Pipeline tool and the MonoGame framework.

Everybody who had the issue here is using MonoGame 3.4 (including me) and this project includes 3.5 libraries.

The XNB format has changed between 3.4 and 3.5 and that is causing the issue.
I got it to work changing the references to MonoGame 3.4 and removing `Window.Icon = new System.Drawing.Icon("Icon.ico");` as that is not supported in MonoGame 3.4.

Samples work flawlessly after doing that.

---
The list of targetPlatformIdentifiers has changed between 3.4 and 3.5.
In 3.4 `'g'` identifies WinGL
In 3.5 `'d'` is used for this platform (and LinuxGL)

https://github.com/mono/MonoGame/blob/master/MonoGame.Framework/Content/ContentManager.cs

https://github.com/mono/MonoGame/blo/develop/MonoGame.Framework/Content/ContentManager.cs

---
To recapitulate: Do not use the 3.4 Content Pipeline Tool and MonoGame Framework 3.5 together :)

**Comment by craftworkgames** [comment]
@Sejsel Great work!

**Comment by craftworkgames** [comment]
This issue is really starting to bother me, since it's blocking people with MonoGame 3.4. I'd rather favor 3.4 users since that's the latest official release.

If anyone has a solution that gets it working with 3.4 and 3.5 together on both platforms please PR. I'm going to look into it more when I get some free time.

**Comment by craftworkgames** [comment]
Okay. I've rolled back everything in the samples repo to MonoGame 3.4.

When MonoGame 3.5 is officially released we'll support it. Until then, this is going to have to do.

**Comment by craftworkgames** [comment]
I believe this issue is now resolved.

**Comment by Taikatou** [comment]
I'm just starting using MonoGame Extended and I have just got this problem. Is there a fix, I am using MonoGame.Framework.WindowsGl 3.4 and MonoGame Extended 0.4.64. Thank you. :)
